# Initialize colors.
#autoload -U colors
#colors
 
# Allow for functions in the prompt.
#setopt PROMPT_SUBST
 
# Autoload zsh functions.
fpath=($1/functions $fpath)
autoload -U $1/functions/*(:t)
 
# Enable auto-execution of functions.
typeset -ga preexec_functions
typeset -ga precmd_functions
typeset -ga chpwd_functions
 
# Append hg functions needed for prompt.
preexec_functions+='preexec_update_hg_vars'
precmd_functions+='precmd_update_hg_vars'
chpwd_functions+='chpwd_update_hg_vars'
 
# Set the prompt.
#PROMPT=$'%{${fg[cyan]}%}%B%~%b$(prompt_hg_info)%{${fg[default]}%} '
